"""order_comment

Revision ID: 7567518c7ba3
Revises: 96b8b2f01e74
Create Date: 2026-02-11 15:31:07.033167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7567518c7ba3'
down_revision: Union[str, Sequence[str], None] = '96b8b2f01e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment')
    # ### end Alembic commands ###
