"""init3

Revision ID: 7e842c40365d
Revises: d2f1615da32f
Create Date: 2026-02-10 19:01:02.174600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e842c40365d'
down_revision: Union[str, Sequence[str], None] = 'd2f1615da32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('street', sa.String(length=60), nullable=True),
    sa.Column('house', sa.String(length=60), nullable=True),
    sa.Column('entrance', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('clients', 'street')
    op.drop_column('clients', 'house')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'entrance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('entrance', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('city', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('house', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('street', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_table('addresses')
    # ### end Alembic commands ###
