"""order model3

Revision ID: 96b8b2f01e74
Revises: f18e9794b668
Create Date: 2026-02-11 09:26:50.444410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b8b2f01e74'
down_revision: Union[str, Sequence[str], None] = 'f18e9794b668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sum_order', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sum_order')
    # ### end Alembic commands ###
