"""init2

Revision ID: d2f1615da32f
Revises: 3918458873dc
Create Date: 2026-02-10 18:08:05.336927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f1615da32f'
down_revision: Union[str, Sequence[str], None] = '3918458873dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('city', sa.String(length=60), nullable=True))
    op.add_column('clients', sa.Column('street', sa.String(length=60), nullable=True))
    op.add_column('clients', sa.Column('house', sa.String(length=60), nullable=True))
    op.add_column('clients', sa.Column('entrance', sa.String(length=60), nullable=True))
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('clients', 'entrance')
    op.drop_column('clients', 'house')
    op.drop_column('clients', 'street')
    op.drop_column('clients', 'city')
    # ### end Alembic commands ###
