"""order models

Revision ID: f18e9794b668
Revises: 7e842c40365d
Create Date: 2026-02-10 21:23:16.779827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f18e9794b668'
down_revision: Union[str, Sequence[str], None] = '7e842c40365d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

orderstatus = sa.Enum(
    "cooking", "completed", "in_delivery", "ending", "cancelled",
    name="orderstatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    orderstatus.create(op.get_bind(), checkfirst=True)
    op.create_table('order_items',
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('qty', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('order_id', 'product_id')
                    )
    op.add_column('orders', sa.Column(
        'address_id', sa.Integer(), nullable=False))
    op.add_column(
        "orders",
        sa.Column("status", orderstatus, nullable=False,
                  server_default="cooking"),
    )
    op.drop_constraint(op.f('orders_product_id_fkey'),
                       'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(
        timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_product_id_fkey'),
                          'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'status')
    orderstatus.drop(op.get_bind(), checkfirst=True)
    op.drop_column('orders', 'address_id')
    op.drop_table('order_items')
    # ### end Alembic commands ###
