"""add in order_items

Revision ID: f671f5f0b7b5
Revises: 4f9ca78f966f
Create Date: 2026-02-20 15:27:23.366856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f671f5f0b7b5'
down_revision: Union[str, Sequence[str], None] = '4f9ca78f966f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('price_retail', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_retail')
    op.drop_column('order_items', 'name')
    # ### end Alembic commands ###
